#!/usr/bin/env python3
"""
Venv Batch Template Generator

A small Windows-friendly Tkinter GUI that generates project-local helper scripts:

- run.bat
- pip.bat
- shell.bat
- doctor.bat

Core idea:
    Do not rely on manual venv activation.
    Call the project's .venv\\Scripts\\python.exe directly.
"""

from __future__ import annotations

import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from tkinter import (
    BooleanVar,
    Button,
    Checkbutton,
    Entry,
    Frame,
    Label,
    LabelFrame,
    Radiobutton,
    StringVar,
    Tk,
    W,
    E,
    BOTH,
    END,
    filedialog,
    messagebox,
)
from tkinter.scrolledtext import ScrolledText


@dataclass(frozen=True)
class GeneratorConfig:
    project_dir: Path
    project_name: str
    venv_dir: str
    entry_mode: str  # "file" or "module"
    app_entry: str
    overwrite_existing: bool
    create_requirements: bool
    include_webengine_check: bool
    pause_on_exit: bool
    create_venv_now: bool


def bat_escape(value: str) -> str:
    return value.replace('"', "")


def make_run_bat(cfg: GeneratorConfig) -> str:
    project_name = bat_escape(cfg.project_name)
    venv_dir = bat_escape(cfg.venv_dir)
    entry_mode = bat_escape(cfg.entry_mode)
    app_entry = bat_escape(cfg.app_entry)
    pause_block = "pause\nexit /b %EXITCODE%\n" if cfg.pause_on_exit else "exit /b %EXITCODE%\n"

    return f'''@echo off
setlocal
cd /d "%~dp0"

rem ============================================================
rem Project Runner
rem Generated by Venv Batch Template Generator
rem
rem ENTRY_MODE:
rem   file   -> .venv\\Scripts\\python.exe app.py
rem   module -> .venv\\Scripts\\python.exe -m package_name
rem ============================================================

set "PROJECT_NAME={project_name}"
set "VENV_DIR={venv_dir}"
set "ENTRY_MODE={entry_mode}"
set "APP_ENTRY={app_entry}"

set "PY=%CD%\\%VENV_DIR%\\Scripts\\python.exe"

if not exist "%PY%" (
    echo [ERROR] Local venv was not found:
    echo         %PY%
    echo.
    echo Create it with:
    echo         python -m venv %VENV_DIR%
    echo         %VENV_DIR%\\Scripts\\python.exe -m pip install --upgrade pip
    echo         %VENV_DIR%\\Scripts\\python.exe -m pip install -r requirements.txt
    echo.
    pause
    exit /b 1
)

if /I "%ENTRY_MODE%"=="file" (
    if not exist "%APP_ENTRY%" (
        echo [ERROR] APP_ENTRY file does not exist:
        echo         %APP_ENTRY%
        echo.
        echo Edit run.bat and set APP_ENTRY to your real launcher file.
        echo.
        pause
        exit /b 1
    )
)

title %PROJECT_NAME% - RUN
echo ============================================================
echo Running: %PROJECT_NAME%
echo Project: %CD%
echo Python : %PY%
echo Mode   : %ENTRY_MODE%
echo Entry  : %APP_ENTRY%
echo ============================================================
echo.

if /I "%ENTRY_MODE%"=="module" (
    "%PY%" -m %APP_ENTRY% %*
) else (
    "%PY%" "%APP_ENTRY%" %*
)

set "EXITCODE=%ERRORLEVEL%"
echo.
echo ============================================================
echo Process exited with code: %EXITCODE%
echo ============================================================
{pause_block}'''


def make_pip_bat(cfg: GeneratorConfig) -> str:
    venv_dir = bat_escape(cfg.venv_dir)
    return f'''@echo off
setlocal
cd /d "%~dp0"

rem ============================================================
rem Project-local pip wrapper
rem
rem Usage:
rem   pip.bat install requests
rem   pip.bat install -r requirements.txt
rem   pip.bat freeze
rem   pip.bat list
rem ============================================================

set "VENV_DIR={venv_dir}"
set "PY=%CD%\\%VENV_DIR%\\Scripts\\python.exe"

if not exist "%PY%" (
    echo [ERROR] Local venv was not found:
    echo         %PY%
    echo.
    echo Create it with:
    echo         python -m venv %VENV_DIR%
    echo.
    pause
    exit /b 1
)

"%PY%" -m pip %*
exit /b %ERRORLEVEL%
'''


def make_shell_bat(cfg: GeneratorConfig) -> str:
    project_name = bat_escape(cfg.project_name)
    venv_dir = bat_escape(cfg.venv_dir)
    return f'''@echo off
cd /d "%~dp0"

rem ============================================================
rem Opens an activated shell for this project only.
rem Use when you deliberately want an interactive venv session.
rem ============================================================

set "PROJECT_NAME={project_name}"
set "VENV_DIR={venv_dir}"
set "ACTIVATE=%CD%\\%VENV_DIR%\\Scripts\\activate.bat"

if not exist "%ACTIVATE%" (
    echo [ERROR] Local venv was not found:
    echo         %ACTIVATE%
    echo.
    echo Create it with:
    echo         python -m venv %VENV_DIR%
    echo.
    pause
    exit /b 1
)

title %PROJECT_NAME% - VENV SHELL
call "%ACTIVATE%"

echo ============================================================
echo Activated project shell
echo Project: %CD%
echo Python :
where python
echo ============================================================
echo.
cmd /k
'''


def make_doctor_bat(cfg: GeneratorConfig) -> str:
    project_name = bat_escape(cfg.project_name)
    venv_dir = bat_escape(cfg.venv_dir)
    entry_mode = bat_escape(cfg.entry_mode)
    app_entry = bat_escape(cfg.app_entry)

    webengine_block = ""
    if cfg.include_webengine_check:
        webengine_block = r'''
echo ------------------------------------------------------------
echo Optional PyQt6 WebEngine check
echo ------------------------------------------------------------
"%PY%" -c "from PyQt6 import QtCore; print('PyQt:', QtCore.PYQT_VERSION_STR); print('Qt   :', QtCore.QT_VERSION_STR); from PyQt6.QtWebEngineWidgets import QWebEngineView; print('WEBENGINE OK')" 2>nul
if errorlevel 1 (
    echo [INFO] PyQt6 WebEngine not available or not required for this project.
) else (
    echo [OK] PyQt6 WebEngine import succeeded.
)
echo.
'''

    return f'''@echo off
setlocal
cd /d "%~dp0"

rem ============================================================
rem Project environment doctor
rem Generated by Venv Batch Template Generator
rem ============================================================

set "PROJECT_NAME={project_name}"
set "VENV_DIR={venv_dir}"
set "ENTRY_MODE={entry_mode}"
set "APP_ENTRY={app_entry}"
set "PY=%CD%\\%VENV_DIR%\\Scripts\\python.exe"

echo ============================================================
echo PROJECT DOCTOR: %PROJECT_NAME%
echo ============================================================
echo Project: %CD%
echo Mode   : %ENTRY_MODE%
echo Entry  : %APP_ENTRY%
echo.

if not exist "%PY%" (
    echo [FAIL] Local venv was not found:
    echo        %PY%
    echo.
    echo Create it with:
    echo        python -m venv %VENV_DIR%
    echo        %VENV_DIR%\\Scripts\\python.exe -m pip install --upgrade pip
    echo.
    pause
    exit /b 1
)

echo [OK] Local venv found:
echo      %PY%
echo.

echo ------------------------------------------------------------
echo Python identity
echo ------------------------------------------------------------
"%PY%" -c "import sys; print('executable:', sys.executable); print('prefix    :', sys.prefix); print('version   :', sys.version)"
echo.

echo ------------------------------------------------------------
echo Pip version
echo ------------------------------------------------------------
"%PY%" -m pip --version
echo.

echo ------------------------------------------------------------
echo Pip dependency check
echo ------------------------------------------------------------
"%PY%" -m pip check
echo.

echo ------------------------------------------------------------
echo Entry point check
echo ------------------------------------------------------------
if /I "%ENTRY_MODE%"=="file" (
    if exist "%APP_ENTRY%" (
        echo [OK] Entry file found: %APP_ENTRY%
    ) else (
        echo [FAIL] Entry file not found: %APP_ENTRY%
    )
) else (
    "%PY%" -c "import importlib.util, sys; name=r'%APP_ENTRY%'; spec=importlib.util.find_spec(name); print('[OK] Module found: ' + name if spec else '[FAIL] Module not found: ' + name); sys.exit(0 if spec else 1)"
)
echo.

echo ------------------------------------------------------------
echo Requirements file check
echo ------------------------------------------------------------
if exist "requirements.txt" (
    echo [OK] requirements.txt found.
) else (
    echo [WARN] requirements.txt not found.
)
if exist "requirements.lock.txt" (
    echo [OK] requirements.lock.txt found.
) else (
    echo [WARN] requirements.lock.txt not found.
)
echo.
{webengine_block}
echo ============================================================
echo DOCTOR COMPLETE
echo ============================================================
pause
exit /b 0
'''


def generate_files(cfg: GeneratorConfig) -> list[Path]:
    cfg.project_dir.mkdir(parents=True, exist_ok=True)
    outputs = {
        "run.bat": make_run_bat(cfg),
        "pip.bat": make_pip_bat(cfg),
        "shell.bat": make_shell_bat(cfg),
        "doctor.bat": make_doctor_bat(cfg),
    }
    written: list[Path] = []
    for filename, content in outputs.items():
        path = cfg.project_dir / filename
        if path.exists() and not cfg.overwrite_existing:
            raise FileExistsError(f"{path} already exists. Enable overwrite to replace it.")
        path.write_text(content, encoding="utf-8", newline="\r\n")
        written.append(path)
    if cfg.create_requirements:
        req = cfg.project_dir / "requirements.txt"
        if not req.exists():
            req.write_text("", encoding="utf-8")
            written.append(req)
    return written


def create_venv(cfg: GeneratorConfig) -> None:
    venv_path = cfg.project_dir / cfg.venv_dir
    if venv_path.exists():
        return
    subprocess.run([sys.executable, "-m", "venv", str(venv_path)], cwd=str(cfg.project_dir), check=True)


class App:
    def __init__(self, root: Tk) -> None:
        self.root = root
        root.title("Venv Batch Template Generator")
        root.minsize(780, 620)

        self.project_dir = StringVar()
        self.project_name = StringVar()
        self.venv_dir = StringVar(value=".venv")
        self.entry_mode = StringVar(value="file")
        self.app_entry = StringVar(value="main.py")
        self.overwrite_existing = BooleanVar(value=False)
        self.create_requirements = BooleanVar(value=True)
        self.include_webengine_check = BooleanVar(value=True)
        self.pause_on_exit = BooleanVar(value=True)
        self.create_venv_now = BooleanVar(value=False)

        self._build_ui()

    def _build_ui(self) -> None:
        outer = Frame(self.root, padx=14, pady=14)
        outer.pack(fill=BOTH, expand=True)

        Label(outer, text="Venv Batch Template Generator", font=("Segoe UI", 16, "bold")).pack(anchor=W)
        Label(outer, text="Generate run.bat, pip.bat, shell.bat and doctor.bat for a Python project.", font=("Segoe UI", 10)).pack(anchor=W, pady=(0, 12))

        project_box = LabelFrame(outer, text="Project", padx=10, pady=10)
        project_box.pack(fill="x", pady=(0, 10))
        project_box.columnconfigure(1, weight=1)

        Label(project_box, text="Project folder:").grid(row=0, column=0, sticky=W, pady=4)
        Entry(project_box, textvariable=self.project_dir).grid(row=0, column=1, sticky=E+W, padx=8)
        Button(project_box, text="Browse...", command=self.browse_project_dir).grid(row=0, column=2, sticky=E)

        Label(project_box, text="Project name:").grid(row=1, column=0, sticky=W, pady=4)
        Entry(project_box, textvariable=self.project_name).grid(row=1, column=1, sticky=E+W, padx=8)
        Button(project_box, text="Use Folder Name", command=self.use_folder_name).grid(row=1, column=2, sticky=E)

        Label(project_box, text="Venv folder:").grid(row=2, column=0, sticky=W, pady=4)
        Entry(project_box, textvariable=self.venv_dir, width=20).grid(row=2, column=1, sticky=W, padx=8)

        entry_box = LabelFrame(outer, text="Entry Point", padx=10, pady=10)
        entry_box.pack(fill="x", pady=(0, 10))
        entry_box.columnconfigure(1, weight=1)

        Radiobutton(entry_box, text="Python file", variable=self.entry_mode, value="file", command=self.on_entry_mode_changed).grid(row=0, column=0, sticky=W)
        Radiobutton(entry_box, text="Python module/package", variable=self.entry_mode, value="module", command=self.on_entry_mode_changed).grid(row=0, column=1, sticky=W)

        Label(entry_box, text="Entry value:").grid(row=1, column=0, sticky=W, pady=4)
        Entry(entry_box, textvariable=self.app_entry).grid(row=1, column=1, sticky=E+W, padx=8)
        Button(entry_box, text="Browse .py...", command=self.browse_entry_file).grid(row=1, column=2, sticky=E)
        Label(entry_box, text='Examples: file mode -> "main.py" / "src\\app.py"; module mode -> "desktop_companion"', foreground="#555555").grid(row=2, column=0, columnspan=3, sticky=W, pady=(4, 0))

        options_box = LabelFrame(outer, text="Options", padx=10, pady=10)
        options_box.pack(fill="x", pady=(0, 10))
        Checkbutton(options_box, text="Overwrite existing .bat files", variable=self.overwrite_existing).grid(row=0, column=0, sticky=W)
        Checkbutton(options_box, text="Create empty requirements.txt if missing", variable=self.create_requirements).grid(row=0, column=1, sticky=W)
        Checkbutton(options_box, text="Include PyQt6 WebEngine check in doctor.bat", variable=self.include_webengine_check).grid(row=1, column=0, sticky=W)
        Checkbutton(options_box, text="Pause when run.bat exits", variable=self.pause_on_exit).grid(row=1, column=1, sticky=W)
        Checkbutton(options_box, text="Create .venv now", variable=self.create_venv_now).grid(row=2, column=0, sticky=W)

        button_row = Frame(outer)
        button_row.pack(fill="x", pady=(2, 10))
        Button(button_row, text="Generate 4 File Set", command=self.on_generate, height=2).pack(side="left")
        Button(button_row, text="Clear Log", command=self.clear_log).pack(side="left", padx=8)

        self.log = ScrolledText(outer, height=14, wrap="word")
        self.log.pack(fill=BOTH, expand=True)
        self.write_log("Ready.\n")
        self.write_log("Tip: for 'python -m desktop_companion', choose module mode and enter desktop_companion.\n")

    def browse_project_dir(self) -> None:
        selected = filedialog.askdirectory(title="Select project folder")
        if selected:
            self.project_dir.set(selected)
            if not self.project_name.get().strip():
                self.use_folder_name()

    def use_folder_name(self) -> None:
        value = self.project_dir.get().strip()
        if value:
            self.project_name.set(Path(value).name)

    def browse_entry_file(self) -> None:
        initial = self.project_dir.get().strip() or os.getcwd()
        selected = filedialog.askopenfilename(title="Select Python entry file", initialdir=initial, filetypes=[("Python files", "*.py"), ("All files", "*.*")])
        if selected:
            p = Path(selected)
            project_raw = self.project_dir.get().strip()
            if project_raw:
                try:
                    self.app_entry.set(str(p.relative_to(Path(project_raw))))
                except ValueError:
                    self.app_entry.set(str(p))
            else:
                self.app_entry.set(str(p))
            self.entry_mode.set("file")

    def on_entry_mode_changed(self) -> None:
        if self.entry_mode.get() == "module":
            if self.app_entry.get().strip() in {"main.py", "app.py"}:
                self.app_entry.set("desktop_companion")
        else:
            if "." not in Path(self.app_entry.get().strip()).name:
                self.app_entry.set("main.py")

    def read_config(self) -> GeneratorConfig:
        project_dir_raw = self.project_dir.get().strip()
        if not project_dir_raw:
            raise ValueError("Select a project folder first.")
        project_dir = Path(project_dir_raw)
        project_name = self.project_name.get().strip() or project_dir.name
        venv_dir = self.venv_dir.get().strip() or ".venv"
        entry_mode = self.entry_mode.get().strip().lower()
        app_entry = self.app_entry.get().strip()
        if entry_mode not in {"file", "module"}:
            raise ValueError("Entry mode must be 'file' or 'module'.")
        if not app_entry:
            raise ValueError("Entry value is required.")
        if entry_mode == "module" and (app_entry.endswith(".py") or "\\" in app_entry or "/" in app_entry):
            raise ValueError("Module mode expects a module/package name, e.g. desktop_companion, not a file path.")
        return GeneratorConfig(project_dir, project_name, venv_dir, entry_mode, app_entry, bool(self.overwrite_existing.get()), bool(self.create_requirements.get()), bool(self.include_webengine_check.get()), bool(self.pause_on_exit.get()), bool(self.create_venv_now.get()))

    def on_generate(self) -> None:
        try:
            cfg = self.read_config()
            self.write_log("\nGenerating templates...\n")
            self.write_log(f"Project: {cfg.project_dir}\nMode   : {cfg.entry_mode}\nEntry  : {cfg.app_entry}\n")
            written = generate_files(cfg)
            for path in written:
                self.write_log(f"[WROTE] {path}\n")
            if cfg.create_venv_now:
                self.write_log("\nCreating .venv...\n")
                create_venv(cfg)
                self.write_log(f"[OK] venv available at {cfg.project_dir / cfg.venv_dir}\n")
            self.write_log("\nDone.\n")
            messagebox.showinfo("Generated", "The project helper files were generated successfully.")
        except Exception as exc:
            self.write_log(f"\n[ERROR] {exc}\n")
            messagebox.showerror("Error", str(exc))

    def write_log(self, text: str) -> None:
        self.log.insert(END, text)
        self.log.see(END)

    def clear_log(self) -> None:
        self.log.delete("1.0", END)


def main() -> None:
    root = Tk()
    App(root)
    root.mainloop()


if __name__ == "__main__":
    main()
