"""
venv_bat_gen.core
=================
All template generation, configuration, project scanning, and preset
management logic.  No GUI imports — safe to use from CLI or tests.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path


# ---------------------------------------------------------------------------
# Regex constants
# ---------------------------------------------------------------------------

# Valid Python module/package name: identifiers separated by dots
MODULE_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)*$")

# Characters that break cmd.exe control flow when unquoted
RUNNER_ARGS_UNSAFE_RE = re.compile(r'[&|<>^"]')


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def bat_escape(value: str) -> str:
    """Escape characters that would break batch variable assignments."""
    value = value.replace('"', "")
    value = value.replace("%", "%%")
    return value


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class GeneratorConfig:
    project_dir:           Path
    project_name:          str
    venv_dir:              str
    entry_mode:            str   # "file" | "module" | "runner"
    app_entry:             str
    runner_args:           str   # runner mode only
    overwrite_existing:    bool
    create_requirements:   bool
    include_webengine_check: bool
    pause_on_exit:         bool
    create_venv_now:       bool
    include_test_bat:      bool
    use_uv:                bool  # use uv instead of pip where possible
    include_posix:         bool  # also generate POSIX .sh equivalents


# ---------------------------------------------------------------------------
# .bat generators
# ---------------------------------------------------------------------------

def make_run_bat(cfg: GeneratorConfig) -> str:
    project_name = bat_escape(cfg.project_name)
    venv_dir     = bat_escape(cfg.venv_dir)
    entry_mode   = bat_escape(cfg.entry_mode)
    app_entry    = bat_escape(cfg.app_entry)
    runner_args  = bat_escape(cfg.runner_args)
    pause_block  = "pause\nexit /b !EXITCODE!\n" if cfg.pause_on_exit else "exit /b !EXITCODE!\n"
    generated_on = datetime.now().strftime("%Y-%m-%d %H:%M")

    return fr'''@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0"

rem ============================================================
rem  Project Runner
rem  Generated by Venv Batch Template Generator (KeystoneAI) v3.2
rem  Generated on: {generated_on}
rem
rem  ENTRY_MODE:
rem    file   -> python app.py
rem    module -> python -m package.module
rem    runner -> python -m runner_module [args...]
rem ============================================================

set "PROJECT_NAME={project_name}"
set "VENV_DIR={venv_dir}"
set "ENTRY_MODE={entry_mode}"
set "APP_ENTRY={app_entry}"
set "RUNNER_ARGS={runner_args}"

set "PY=%CD%\%VENV_DIR%\Scripts\python.exe"

if not exist "%PY%" (
    echo [ERROR] Local venv not found: "%PY%"
    echo.
    echo Fix with:
    echo   python -m venv "%VENV_DIR%"
    echo   "%VENV_DIR%\Scripts\python.exe" -m pip install --upgrade pip
    echo   "%VENV_DIR%\Scripts\python.exe" -m pip install -r requirements.txt
    echo.
    pause
    exit /b 1
)

if /I "%ENTRY_MODE%"=="file" if not exist "%APP_ENTRY%" (
    echo [ERROR] Entry file not found: "%APP_ENTRY%"
    echo Edit run.bat or run with the correct entry file.
    pause
    exit /b 1
)

title "%PROJECT_NAME% - RUN"
echo ============================================================
echo  Running : %PROJECT_NAME%
echo  Project : %CD%
echo  Python  : %PY%
echo  Mode    : %ENTRY_MODE%
echo  Entry   : %APP_ENTRY%
if /I "%ENTRY_MODE%"=="runner" echo  Args    : %RUNNER_ARGS%
echo ============================================================
echo.

set "EXITCODE=0"

if /I "%ENTRY_MODE%"=="module" (
    "%PY%" -m %APP_ENTRY% %*
) else if /I "%ENTRY_MODE%"=="runner" (
    if defined RUNNER_ARGS (
        "%PY%" -m %APP_ENTRY% !RUNNER_ARGS! %*
    ) else (
        "%PY%" -m %APP_ENTRY% %*
    )
) else (
    "%PY%" "%APP_ENTRY%" %*
)

set "EXITCODE=!ERRORLEVEL!"

echo.
echo ============================================================
echo  Process exited with code: !EXITCODE!
echo ============================================================
{pause_block}'''


def make_pip_bat(cfg: GeneratorConfig) -> str:
    venv_dir     = bat_escape(cfg.venv_dir)
    generated_on = datetime.now().strftime("%Y-%m-%d %H:%M")

    if cfg.use_uv:
        return f'''@echo off
setlocal
cd /d "%~dp0"

rem ============================================================
rem  Project-local uv pip wrapper
rem  Generated by Venv Batch Template Generator (KeystoneAI) v3.2
rem  Generated on: {generated_on}
rem
rem  Usage:
rem    pip.bat install requests
rem    pip.bat install -r requirements.txt
rem    pip.bat freeze > requirements.txt
rem    pip.bat list
rem    pip.bat uninstall requests
rem ============================================================

set "VENV_DIR={venv_dir}"

where uv >nul 2>&1
if errorlevel 1 (
    echo [ERROR] uv is not installed or not on PATH.
    echo         Install it with: pip install uv
    echo         Or see: https://github.com/astral-sh/uv
    pause
    exit /b 1
)

uv pip --python "%CD%\\%VENV_DIR%\\Scripts\\python.exe" %*
exit /b %ERRORLEVEL%
'''
    else:
        return f'''@echo off
setlocal
cd /d "%~dp0"

rem ============================================================
rem  Project-local pip wrapper
rem  Generated by Venv Batch Template Generator (KeystoneAI) v3.2
rem  Generated on: {generated_on}
rem
rem  Usage:
rem    pip.bat install requests
rem    pip.bat install -r requirements.txt
rem    pip.bat freeze > requirements.txt
rem    pip.bat list
rem    pip.bat uninstall requests
rem ============================================================

set "VENV_DIR={venv_dir}"
set "PY=%CD%\\%VENV_DIR%\\Scripts\\python.exe"

if not exist "%PY%" (
    echo [ERROR] Local venv was not found:
    echo         "%PY%"
    echo.
    echo Create it with:
    echo         python -m venv "%VENV_DIR%"
    echo.
    pause
    exit /b 1
)

"%PY%" -m pip %*
exit /b %ERRORLEVEL%
'''


def make_shell_bat(cfg: GeneratorConfig) -> str:
    project_name = bat_escape(cfg.project_name)
    venv_dir     = bat_escape(cfg.venv_dir)
    generated_on = datetime.now().strftime("%Y-%m-%d %H:%M")
    return f'''@echo off
cd /d "%~dp0"

rem ============================================================
rem  Project venv shell
rem  Generated by Venv Batch Template Generator (KeystoneAI) v3.2
rem  Generated on: {generated_on}
rem
rem  Opens an activated CMD session for this project.
rem  Use only when you need an interactive venv session.
rem  Exit with: exit
rem ============================================================

set "PROJECT_NAME={project_name}"
set "VENV_DIR={venv_dir}"
set "ACTIVATE=%CD%\\%VENV_DIR%\\Scripts\\activate.bat"

if not exist "%ACTIVATE%" (
    echo [ERROR] Local venv was not found:
    echo         "%ACTIVATE%"
    echo.
    echo Create it with:
    echo         python -m venv "%VENV_DIR%"
    echo.
    pause
    exit /b 1
)

title "%PROJECT_NAME% - VENV SHELL"
call "%ACTIVATE%"

echo ============================================================
echo  Project shell activated
echo  Project: "%CD%"
echo  Python :
where python
echo  Type "exit" to leave this shell.
echo ============================================================
echo.
cmd /k
'''


def make_sync_bat(cfg: GeneratorConfig) -> str:
    project_name = bat_escape(cfg.project_name)
    venv_dir     = bat_escape(cfg.venv_dir)
    generated_on = datetime.now().strftime("%Y-%m-%d %H:%M")

    if cfg.use_uv:
        return f'''@echo off
setlocal
cd /d "%~dp0"

rem ============================================================
rem  Dependency Sync (uv)
rem  Generated by Venv Batch Template Generator (KeystoneAI) v3.2
rem  Generated on: {generated_on}
rem ============================================================

set "PROJECT_NAME={project_name}"
set "VENV_DIR={venv_dir}"
set "PY=%CD%\\%VENV_DIR%\\Scripts\\python.exe"

where uv >nul 2>&1
if errorlevel 1 (
    echo [ERROR] uv is not installed or not on PATH.
    echo         Install with: pip install uv
    echo         https://github.com/astral-sh/uv
    pause
    exit /b 1
)

title "%PROJECT_NAME% - SYNC (uv)"

echo ============================================================
echo  Syncing: %PROJECT_NAME%  [uv]
echo ============================================================
echo.

if exist "uv.lock" (
    echo [1/2] Running uv sync ^(uv.lock detected^)...
    echo ============================================================
    uv sync
    echo.
) else if exist "pyproject.toml" (
    echo [1/2] Running uv sync ^(pyproject.toml detected^)...
    echo ============================================================
    uv sync
    echo.
) else if exist "requirements.txt" (
    echo [1/2] Installing from requirements.txt...
    echo ============================================================
    uv pip install --python "%PY%" -r requirements.txt
    echo.
) else (
    echo [WARN] No uv.lock, pyproject.toml, or requirements.txt found.
    echo       Nothing to sync.
    echo.
)

echo [2/2] Dependency health check...
echo ============================================================
uv pip check --python "%PY%"
echo.

echo ============================================================
echo  SYNC COMPLETE  (uv)
echo ============================================================
pause
exit /b 0
'''
    else:
        return f'''@echo off
setlocal
cd /d "%~dp0"

rem ============================================================
rem  Dependency Sync (pip)
rem  Generated by Venv Batch Template Generator (KeystoneAI) v3.2
rem  Generated on: {generated_on}
rem ============================================================

set "PROJECT_NAME={project_name}"
set "VENV_DIR={venv_dir}"
set "PY=%CD%\\%VENV_DIR%\\Scripts\\python.exe"

if not exist "%PY%" (
    echo [ERROR] Local venv not found: "%PY%"
    echo.
    echo Create it with:
    echo   python -m venv "%VENV_DIR%"
    pause
    exit /b 1
)

title "%PROJECT_NAME% - SYNC"

echo ============================================================
echo  Syncing: %PROJECT_NAME%
echo  Python : %PY%
echo ============================================================
echo.

echo [1/3] Upgrading pip...
echo ============================================================
"%PY%" -m pip install --upgrade pip
echo.

if exist "requirements.txt" (
    echo [2/3] Installing from requirements.txt...
    echo ============================================================
    "%PY%" -m pip install -r requirements.txt
    echo.
) else (
    echo [2/3] SKIPPED: No requirements.txt found.
    echo       Create one with: pip.bat freeze ^> requirements.txt
    echo.
)

echo [3/3] Dependency health check...
echo ============================================================
"%PY%" -m pip check
echo.

echo ============================================================
echo  SYNC COMPLETE
echo ============================================================
pause
exit /b 0
'''


def make_doctor_bat(cfg: GeneratorConfig) -> str:
    project_name = bat_escape(cfg.project_name)
    venv_dir     = bat_escape(cfg.venv_dir)
    entry_mode   = bat_escape(cfg.entry_mode)
    app_entry    = bat_escape(cfg.app_entry)
    runner_args  = bat_escape(cfg.runner_args)
    generated_on = datetime.now().strftime("%Y-%m-%d %H:%M")

    uv_block = ""
    if cfg.use_uv:
        uv_block = r'''
echo ------------------------------------------------------------
echo  uv status
echo ------------------------------------------------------------
where uv >nul 2>&1
if errorlevel 1 (
    echo [WARN] uv not found on PATH.
    echo        Install: pip install uv
) else (
    uv --version
    echo [OK] uv is available.
)
echo.
'''

    webengine_block = ""
    if cfg.include_webengine_check:
        webengine_block = r'''
echo ------------------------------------------------------------
echo  PyQt6 WebEngine Check
echo ------------------------------------------------------------
"%PY%" -c "from PyQt6 import QtCore; print('PyQt:', QtCore.PYQT_VERSION_STR); print('Qt  :', QtCore.QT_VERSION_STR); from PyQt6.QtWebEngineWidgets import QWebEngineView; print('[OK] WebEngine imported successfully.')" 2>&1
if errorlevel 1 (
    echo [FAIL] PyQt6 WebEngine check failed.
    echo        Run manually for full traceback:
    echo        "%PY%" -c "from PyQt6.QtWebEngineWidgets import QWebEngineView"
) else (
    echo [OK] PyQt6 WebEngine is available.
)
echo.
'''

    return fr'''@echo off
setlocal
cd /d "%~dp0"

rem ============================================================
rem  Project Doctor
rem  Generated by Venv Batch Template Generator (KeystoneAI) v3.2
rem  Generated on: {generated_on}
rem ============================================================

set "PROJECT_NAME={project_name}"
set "VENV_DIR={venv_dir}"
set "ENTRY_MODE={entry_mode}"
set "APP_ENTRY={app_entry}"
set "RUNNER_ARGS={runner_args}"
set "PY=%CD%\%VENV_DIR%\Scripts\python.exe"

echo ============================================================
echo  PROJECT DOCTOR: %PROJECT_NAME%
echo ============================================================
echo  Project : %CD%
echo  Mode    : %ENTRY_MODE%
echo  Entry   : %APP_ENTRY%
if /I "%ENTRY_MODE%"=="runner" echo  Args    : %RUNNER_ARGS%
echo.

if not exist "%PY%" (
    echo [FAIL] venv not found at: "%PY%"
    echo.
    echo Create it with:
    echo   python -m venv "%VENV_DIR%"
    pause
    exit /b 1
)

echo [OK] venv found: "%PY%"
echo.

echo ------------------------------------------------------------
echo  Python Environment
echo ------------------------------------------------------------
"%PY%" -c "import sys; print('Executable :', sys.executable); print('Version    :', sys.version.split()[0]); print('Prefix     :', sys.prefix)"
echo.

echo ------------------------------------------------------------
echo  pip version
echo ------------------------------------------------------------
"%PY%" -m pip --version
echo.
{uv_block}
echo ------------------------------------------------------------
echo  Installed Packages
echo ------------------------------------------------------------
"%PY%" -m pip list
echo.

echo ------------------------------------------------------------
echo  Dependency Health
echo ------------------------------------------------------------
"%PY%" -m pip check
echo.

echo ------------------------------------------------------------
echo  Entry Point Check
echo ------------------------------------------------------------
if /I "%ENTRY_MODE%"=="file" (
    if exist "%APP_ENTRY%" (
        echo [OK] Entry file found: "%APP_ENTRY%"
    ) else (
        echo [FAIL] Entry file NOT found: "%APP_ENTRY%"
    )
) else (
    "%PY%" -c "import importlib.util, sys; name=r'%APP_ENTRY%'; spec=importlib.util.find_spec(name); print(('[OK] Module found: ' if spec else '[FAIL] Module NOT found: ') + name); sys.exit(0 if spec else 1)" 2>nul
    if errorlevel 1 echo [FAIL] Module import test failed.
    if /I "%ENTRY_MODE%"=="runner" echo [INFO] Runner args: "%RUNNER_ARGS%"
)
echo.

echo ------------------------------------------------------------
echo  Project Files
echo ------------------------------------------------------------
if exist "uv.lock"          echo [OK]   uv.lock found
if exist "pyproject.toml"   echo [OK]   pyproject.toml found
if exist "requirements.txt" echo [OK]   requirements.txt found
if not exist "requirements.txt" echo [WARN] requirements.txt missing
echo.
{webengine_block}
echo ============================================================
echo  DOCTOR COMPLETE
echo ============================================================
pause
exit /b 0
'''


def make_test_bat(cfg: GeneratorConfig) -> str:
    project_name = bat_escape(cfg.project_name)
    venv_dir     = bat_escape(cfg.venv_dir)
    generated_on = datetime.now().strftime("%Y-%m-%d %H:%M")
    return f'''@echo off
setlocal
cd /d "%~dp0"

rem ============================================================
rem  Project test runner
rem  Generated by Venv Batch Template Generator (KeystoneAI) v3.2
rem  Generated on: {generated_on}
rem
rem  Runs pytest via the project-local venv Python.
rem
rem  Usage:
rem    test.bat                        (run all tests)
rem    test.bat tests/test_core.py     (run a specific file)
rem    test.bat -k mapper              (filter by name)
rem    test.bat -v --tb=short          (verbose with short tracebacks)
rem ============================================================

set "PROJECT_NAME={project_name}"
set "VENV_DIR={venv_dir}"
set "PY=%CD%\\%VENV_DIR%\\Scripts\\python.exe"

if not exist "%PY%" (
    echo [ERROR] Local venv was not found:
    echo         "%PY%"
    echo.
    pause
    exit /b 1
)

title "%PROJECT_NAME% - TEST"
echo ============================================================
echo  Testing: "%PROJECT_NAME%"
echo  Python : "%PY%"
echo ============================================================
echo.

"%PY%" -m pytest -v %*
set "EXITCODE=%ERRORLEVEL%"

echo.
echo ============================================================
if "%EXITCODE%"=="0" (
    echo  TESTS PASSED
) else (
    echo  TESTS FAILED  ^(exit code: %EXITCODE%^)
)
echo ============================================================
pause
exit /b %EXITCODE%
'''


# ---------------------------------------------------------------------------
# POSIX shell generators  (.sh equivalents)
# ---------------------------------------------------------------------------

def _sh_escape(value: str) -> str:
    """Escape a value for safe embedding in a bash double-quoted string."""
    # Escape backslash, dollar, backtick, double-quote
    for ch in ('\\', '$', '`', '"'):
        value = value.replace(ch, '\\' + ch)
    return value


def make_run_sh(cfg: GeneratorConfig) -> str:
    project_name = _sh_escape(cfg.project_name)
    venv_dir     = _sh_escape(cfg.venv_dir)
    entry_mode   = _sh_escape(cfg.entry_mode)
    app_entry    = _sh_escape(cfg.app_entry)
    runner_args  = _sh_escape(cfg.runner_args)
    pause_block  = 'read -r -p "Press Enter to continue..." _' if cfg.pause_on_exit else ""
    generated_on = datetime.now().strftime("%Y-%m-%d %H:%M")

    return f'''#!/usr/bin/env bash
# ============================================================
# Project Runner
# Generated by Venv Batch Template Generator (KeystoneAI) v3.2
# Generated on: {generated_on}
#
# ENTRY_MODE:
#   file   -> python app.py
#   module -> python -m package.module
#   runner -> python -m runner_module [args...]
# ============================================================
set -euo pipefail
cd "$(dirname "$0")"

PROJECT_NAME="{project_name}"
VENV_DIR="{venv_dir}"
ENTRY_MODE="{entry_mode}"
APP_ENTRY="{app_entry}"
RUNNER_ARGS="{runner_args}"

PY="$PWD/$VENV_DIR/bin/python"

if [[ ! -x "$PY" ]]; then
    echo "[ERROR] Local venv not found: $PY"
    echo ""
    echo "Create it with:"
    echo "    python3 -m venv \\"$VENV_DIR\\""
    echo "    \\"$VENV_DIR/bin/python\\" -m pip install --upgrade pip"
    echo "    \\"$VENV_DIR/bin/python\\" -m pip install -r requirements.txt"
    exit 1
fi

if [[ "$ENTRY_MODE" == "file" && ! -f "$APP_ENTRY" ]]; then
    echo "[ERROR] Entry file not found: $APP_ENTRY"
    echo "Edit run.sh or specify correct entry point."
    exit 1
fi

echo "============================================================"
echo " Running : $PROJECT_NAME"
echo " Project : $PWD"
echo " Python  : $PY"
echo " Mode    : $ENTRY_MODE"
echo " Entry   : $APP_ENTRY"
[[ -n "$RUNNER_ARGS" && "$ENTRY_MODE" == "runner" ]] && echo " Args    : $RUNNER_ARGS"
echo "============================================================"
echo ""

EXITCODE=0

if [[ "$ENTRY_MODE" == "module" ]]; then
    "$PY" -m "$APP_ENTRY" "$@" || EXITCODE=$?
elif [[ "$ENTRY_MODE" == "runner" ]]; then
    if [[ -n "$RUNNER_ARGS" ]]; then
        # shellcheck disable=SC2086
        "$PY" -m "$APP_ENTRY" $RUNNER_ARGS "$@" || EXITCODE=$?
    else
        "$PY" -m "$APP_ENTRY" "$@" || EXITCODE=$?
    fi
else
    "$PY" "$APP_ENTRY" "$@" || EXITCODE=$?
fi

echo ""
echo "============================================================"
echo " Process exited with code: $EXITCODE"
echo "============================================================"
{pause_block}
exit $EXITCODE
'''


def make_pip_sh(cfg: GeneratorConfig) -> str:
    venv_dir     = _sh_escape(cfg.venv_dir)
    generated_on = datetime.now().strftime("%Y-%m-%d %H:%M")

    if cfg.use_uv:
        return f'''#!/usr/bin/env bash
# ============================================================
# Project-local uv pip wrapper
# Generated by Venv Batch Template Generator (KeystoneAI) v3.2
# Generated on: {generated_on}
#
# Usage:
#   ./pip.sh install requests
#   ./pip.sh install -r requirements.txt
#   ./pip.sh freeze > requirements.txt
#   ./pip.sh list
# ============================================================
set -euo pipefail
cd "$(dirname "$0")"

VENV_DIR="{venv_dir}"

if ! command -v uv &>/dev/null; then
    echo "[ERROR] uv is not installed or not on PATH."
    echo "        Install: pip install uv  or  https://github.com/astral-sh/uv"
    exit 1
fi

uv pip --python "$PWD/$VENV_DIR/bin/python" "$@"
'''
    else:
        return f'''#!/usr/bin/env bash
# ============================================================
# Project-local pip wrapper
# Generated by Venv Batch Template Generator (KeystoneAI) v3.2
# Generated on: {generated_on}
#
# Usage:
#   ./pip.sh install requests
#   ./pip.sh install -r requirements.txt
#   ./pip.sh freeze > requirements.txt
#   ./pip.sh list
# ============================================================
set -euo pipefail
cd "$(dirname "$0")"

VENV_DIR="{venv_dir}"
PY="$PWD/$VENV_DIR/bin/python"

if [[ ! -x "$PY" ]]; then
    echo "[ERROR] Local venv was not found: $PY"
    echo "        Create it with: python3 -m venv \\"$VENV_DIR\\""
    exit 1
fi

"$PY" -m pip "$@"
'''


def make_shell_sh(cfg: GeneratorConfig) -> str:
    project_name = _sh_escape(cfg.project_name)
    venv_dir     = _sh_escape(cfg.venv_dir)
    generated_on = datetime.now().strftime("%Y-%m-%d %H:%M")
    return f'''#!/usr/bin/env bash
# ============================================================
# Project venv shell
# Generated by Venv Batch Template Generator (KeystoneAI) v3.2
# Generated on: {generated_on}
#
# Opens an activated shell session for this project.
# Exit with: exit  or  Ctrl-D
# ============================================================
set -euo pipefail
cd "$(dirname "$0")"

PROJECT_NAME="{project_name}"
VENV_DIR="{venv_dir}"
ACTIVATE="$PWD/$VENV_DIR/bin/activate"

if [[ ! -f "$ACTIVATE" ]]; then
    echo "[ERROR] Local venv was not found: $ACTIVATE"
    echo "        Create it with: python3 -m venv \\"$VENV_DIR\\""
    exit 1
fi

echo "============================================================"
echo " Project shell: $PROJECT_NAME"
echo " Project : $PWD"
echo " Activate: $ACTIVATE"
echo " Type 'exit' or Ctrl-D to leave."
echo "============================================================"
echo ""

# Source the activate script in a subshell so the user gets a clean exit
bash --rcfile <(echo "source '$ACTIVATE'; PS1='($PROJECT_NAME) \\\\u@\\\\h:\\\\w\\\\$ '")
'''


def make_sync_sh(cfg: GeneratorConfig) -> str:
    project_name = _sh_escape(cfg.project_name)
    venv_dir     = _sh_escape(cfg.venv_dir)
    generated_on = datetime.now().strftime("%Y-%m-%d %H:%M")

    if cfg.use_uv:
        return f'''#!/usr/bin/env bash
# ============================================================
# Dependency Sync (uv)
# Generated by Venv Batch Template Generator (KeystoneAI) v3.2
# Generated on: {generated_on}
# ============================================================
set -euo pipefail
cd "$(dirname "$0")"

PROJECT_NAME="{project_name}"
VENV_DIR="{venv_dir}"
PY="$PWD/$VENV_DIR/bin/python"

if ! command -v uv &>/dev/null; then
    echo "[ERROR] uv is not installed or not on PATH."
    echo "        Install: pip install uv"
    echo "        https://github.com/astral-sh/uv"
    exit 1
fi

echo "============================================================"
echo " Syncing: $PROJECT_NAME  [uv]"
echo "============================================================"
echo ""

if [[ -f "uv.lock" ]]; then
    echo "[1/2] Running uv sync (uv.lock detected)..."
    uv sync
elif [[ -f "pyproject.toml" ]]; then
    echo "[1/2] Running uv sync (pyproject.toml detected)..."
    uv sync
elif [[ -f "requirements.txt" ]]; then
    echo "[1/2] Installing from requirements.txt..."
    uv pip install --python "$PY" -r requirements.txt
else
    echo "[WARN] No uv.lock, pyproject.toml, or requirements.txt found."
    echo "      Nothing to sync."
fi
echo ""

echo "[2/2] Dependency health check..."
uv pip check --python "$PY"
echo ""

echo "============================================================"
echo " SYNC COMPLETE  (uv)"
echo "============================================================"
'''
    else:
        return f'''#!/usr/bin/env bash
# ============================================================
# Dependency Sync (pip)
# Generated by Venv Batch Template Generator (KeystoneAI) v3.2
# Generated on: {generated_on}
# ============================================================
set -euo pipefail
cd "$(dirname "$0")"

PROJECT_NAME="{project_name}"
VENV_DIR="{venv_dir}"
PY="$PWD/$VENV_DIR/bin/python"

if [[ ! -x "$PY" ]]; then
    echo "[ERROR] Local venv not found: $PY"
    echo "Create it with: python3 -m venv \\"$VENV_DIR\\""
    exit 1
fi

echo "============================================================"
echo " Syncing: $PROJECT_NAME"
echo " Python : $PY"
echo "============================================================"
echo ""

echo "[1/3] Upgrading pip..."
"$PY" -m pip install --upgrade pip
echo ""

if [[ -f "requirements.txt" ]]; then
    echo "[2/3] Installing from requirements.txt..."
    "$PY" -m pip install -r requirements.txt
else
    echo "[2/3] SKIPPED: No requirements.txt found."
    echo "      Create one with: ./pip.sh freeze > requirements.txt"
fi
echo ""

echo "[3/3] Dependency health check..."
"$PY" -m pip check
echo ""

echo "============================================================"
echo " SYNC COMPLETE"
echo "============================================================"
'''


def make_doctor_sh(cfg: GeneratorConfig) -> str:
    project_name = _sh_escape(cfg.project_name)
    venv_dir     = _sh_escape(cfg.venv_dir)
    entry_mode   = _sh_escape(cfg.entry_mode)
    app_entry    = _sh_escape(cfg.app_entry)
    runner_args  = _sh_escape(cfg.runner_args)
    generated_on = datetime.now().strftime("%Y-%m-%d %H:%M")

    uv_block = ""
    if cfg.use_uv:
        uv_block = '''
echo "------------------------------------------------------------"
echo " uv status"
echo "------------------------------------------------------------"
if command -v uv &>/dev/null; then
    uv --version
    echo "[OK] uv is available."
else
    echo "[WARN] uv not found on PATH."
    echo "       Install: pip install uv"
fi
echo ""
'''

    webengine_block = ""
    if cfg.include_webengine_check:
        webengine_block = '''
echo "------------------------------------------------------------"
echo " PyQt6 WebEngine Check"
echo "------------------------------------------------------------"
if "$PY" -c "
from PyQt6 import QtCore
print('PyQt:', QtCore.PYQT_VERSION_STR)
print('Qt  :', QtCore.QT_VERSION_STR)
from PyQt6.QtWebEngineWidgets import QWebEngineView
print('[OK] WebEngine imported successfully.')
" 2>&1; then
    echo "[OK] PyQt6 WebEngine is available."
else
    echo "[FAIL] PyQt6 WebEngine check failed."
    echo "       Run manually:"
    echo "       $PY -c \\"from PyQt6.QtWebEngineWidgets import QWebEngineView\\""
fi
echo ""
'''

    return f'''#!/usr/bin/env bash
# ============================================================
# Project Doctor
# Generated by Venv Batch Template Generator (KeystoneAI) v3.2
# Generated on: {generated_on}
# ============================================================
set -uo pipefail
cd "$(dirname "$0")"

PROJECT_NAME="{project_name}"
VENV_DIR="{venv_dir}"
ENTRY_MODE="{entry_mode}"
APP_ENTRY="{app_entry}"
RUNNER_ARGS="{runner_args}"
PY="$PWD/$VENV_DIR/bin/python"

echo "============================================================"
echo " PROJECT DOCTOR: $PROJECT_NAME"
echo "============================================================"
echo " Project : $PWD"
echo " Mode    : $ENTRY_MODE"
echo " Entry   : $APP_ENTRY"
[[ "$ENTRY_MODE" == "runner" ]] && echo " Args    : $RUNNER_ARGS"
echo ""

if [[ ! -x "$PY" ]]; then
    echo "[FAIL] venv not found: $PY"
    echo "Create it with: python3 -m venv \\"$VENV_DIR\\""
    exit 1
fi

echo "[OK] venv found: $PY"
echo ""

echo "------------------------------------------------------------"
echo " Python Environment"
echo "------------------------------------------------------------"
"$PY" -c "
import sys
print('Executable :', sys.executable)
print('Version    :', sys.version.split()[0])
print('Prefix     :', sys.prefix)
"
echo ""

echo "------------------------------------------------------------"
echo " pip version"
echo "------------------------------------------------------------"
"$PY" -m pip --version
echo ""
{uv_block}
echo "------------------------------------------------------------"
echo " Installed Packages"
echo "------------------------------------------------------------"
"$PY" -m pip list
echo ""

echo "------------------------------------------------------------"
echo " Dependency Health"
echo "------------------------------------------------------------"
"$PY" -m pip check
echo ""

echo "------------------------------------------------------------"
echo " Entry Point Check"
echo "------------------------------------------------------------"
if [[ "$ENTRY_MODE" == "file" ]]; then
    if [[ -f "$APP_ENTRY" ]]; then
        echo "[OK] Entry file found: $APP_ENTRY"
    else
        echo "[FAIL] Entry file NOT found: $APP_ENTRY"
    fi
else
    if "$PY" -c "
import importlib.util, sys
spec = importlib.util.find_spec('$APP_ENTRY')
print(('[OK] Module found: ' if spec else '[FAIL] Module NOT found: ') + '$APP_ENTRY')
sys.exit(0 if spec else 1)
" 2>/dev/null; then
        :
    else
        echo "[FAIL] Module import test failed."
    fi
    [[ "$ENTRY_MODE" == "runner" ]] && echo "[INFO] Runner args: $RUNNER_ARGS"
fi
echo ""

echo "------------------------------------------------------------"
echo " Project Files"
echo "------------------------------------------------------------"
[[ -f "uv.lock" ]]          && echo "[OK]   uv.lock found"
[[ -f "pyproject.toml" ]]   && echo "[OK]   pyproject.toml found"
[[ -f "requirements.txt" ]] && echo "[OK]   requirements.txt found" || echo "[WARN] requirements.txt missing"
echo ""
{webengine_block}
echo "============================================================"
echo " DOCTOR COMPLETE"
echo "============================================================"
'''


def make_test_sh(cfg: GeneratorConfig) -> str:
    project_name = _sh_escape(cfg.project_name)
    venv_dir     = _sh_escape(cfg.venv_dir)
    generated_on = datetime.now().strftime("%Y-%m-%d %H:%M")
    return f'''#!/usr/bin/env bash
# ============================================================
# Project test runner
# Generated by Venv Batch Template Generator (KeystoneAI) v3.2
# Generated on: {generated_on}
#
# Usage:
#   ./test.sh                      (run all tests)
#   ./test.sh tests/test_core.py   (specific file)
#   ./test.sh -k mapper            (filter by name)
#   ./test.sh -v --tb=short        (verbose)
# ============================================================
set -euo pipefail
cd "$(dirname "$0")"

PROJECT_NAME="{project_name}"
VENV_DIR="{venv_dir}"
PY="$PWD/$VENV_DIR/bin/python"

if [[ ! -x "$PY" ]]; then
    echo "[ERROR] Local venv was not found: $PY"
    exit 1
fi

echo "============================================================"
echo " Testing: $PROJECT_NAME"
echo " Python : $PY"
echo "============================================================"
echo ""

"$PY" -m pytest -v "$@"
EXITCODE=$?

echo ""
echo "============================================================"
if [[ $EXITCODE -eq 0 ]]; then
    echo " TESTS PASSED"
else
    echo " TESTS FAILED  (exit code: $EXITCODE)"
fi
echo "============================================================"
exit $EXITCODE
'''


# ---------------------------------------------------------------------------
# File generation
# ---------------------------------------------------------------------------

def build_previews(cfg: GeneratorConfig) -> dict[str, str]:
    """Return {filename: content} for all scripts included by cfg."""
    previews = {
        "run.bat":    make_run_bat(cfg),
        "pip.bat":    make_pip_bat(cfg),
        "shell.bat":  make_shell_bat(cfg),
        "sync.bat":   make_sync_bat(cfg),
        "doctor.bat": make_doctor_bat(cfg),
    }
    if cfg.include_test_bat:
        previews["test.bat"] = make_test_bat(cfg)

    if cfg.include_posix:
        previews["run.sh"]    = make_run_sh(cfg)
        previews["pip.sh"]    = make_pip_sh(cfg)
        previews["shell.sh"]  = make_shell_sh(cfg)
        previews["sync.sh"]   = make_sync_sh(cfg)
        previews["doctor.sh"] = make_doctor_sh(cfg)
        if cfg.include_test_bat:
            previews["test.sh"] = make_test_sh(cfg)

    return previews


def generate_files(cfg: GeneratorConfig) -> list[Path]:
    """Write all scripts to cfg.project_dir and return list of written paths."""
    import os as _os
    import stat as _stat

    cfg.project_dir.mkdir(parents=True, exist_ok=True)
    outputs = build_previews(cfg)

    written: list[Path] = []
    for filename, content in outputs.items():
        path = cfg.project_dir / filename
        if path.exists() and not cfg.overwrite_existing:
            raise FileExistsError(
                f"{path.name} already exists in that folder.\n"
                "Enable 'Overwrite existing files' to replace it."
            )
        is_sh = filename.endswith(".sh")
        # .sh files: Unix LF line endings; .bat files: Windows CRLF
        path.write_text(content, encoding="utf-8", newline="\n" if is_sh else "\r\n")
        if is_sh:
            # make executable (owner+group+other execute bits)
            current = _os.stat(path).st_mode
            _os.chmod(path, current | _stat.S_IXUSR | _stat.S_IXGRP | _stat.S_IXOTH)
        written.append(path)

    if cfg.create_requirements:
        req = cfg.project_dir / "requirements.txt"
        if not req.exists():
            req.write_text("", encoding="utf-8")
            written.append(req)

    return written


def create_venv(cfg: GeneratorConfig) -> None:
    """Create a venv at cfg.project_dir / cfg.venv_dir using uv or stdlib.

    If use_uv is True but uv is not installed, falls back to python -m venv
    rather than crashing — matching the graceful behaviour of the generated scripts.
    """
    import shutil as _shutil
    venv_path = cfg.project_dir / cfg.venv_dir
    if venv_path.exists():
        return
    if cfg.use_uv and _shutil.which("uv"):
        subprocess.run(["uv", "venv", str(venv_path)], cwd=str(cfg.project_dir), check=True)
    else:
        if cfg.use_uv:
            print(
                "[WARN] uv not found on PATH — falling back to python -m venv",
                file=sys.stderr,
            )
        subprocess.run(
            [sys.executable, "-m", "venv", str(venv_path)],
            cwd=str(cfg.project_dir),
            check=True,
        )


# ---------------------------------------------------------------------------
# Project folder scanner
# ---------------------------------------------------------------------------

@dataclass
class FolderScan:
    venv_found:            bool
    venv_path:             Path | None
    has_requirements:      bool
    has_pyproject:         bool
    has_setup_py:          bool
    has_uv_lock:           bool
    suggested_entry_mode:  str | None
    suggested_app_entry:   str | None
    suggested_runner_args: str | None
    suggested_use_uv:      bool
    suggested_use_posix:   bool
    hints:                 list[str]


# keyword → (entry_mode, app_entry, runner_args)
_PYPROJECT_HINTS: list[tuple[str, str, str, str]] = [
    ("uvicorn",   "runner", "uvicorn",   "app.main:app --host 0.0.0.0 --port 8000 --reload"),
    ("fastapi",   "runner", "uvicorn",   "app.main:app --host 0.0.0.0 --port 8000 --reload"),
    ("streamlit", "runner", "streamlit", "run app.py"),
    ("flask",     "runner", "flask",     "run --debug"),
    ("pyqt6",     "file",   "main.py",   ""),
    ("pyside6",   "file",   "main.py",   ""),
    ("typer",     "module", "app",       ""),
    ("click",     "module", "app",       ""),
]

# uv indicators in pyproject.toml
_UV_INDICATORS = ("[tool.uv]", "uv.lock", "[build-system]")


def scan_project_folder(folder: Path, venv_dir: str = ".venv") -> FolderScan:
    """Inspect folder and return a FolderScan. Pure function, no side effects."""
    hints: list[str] = []

    # venv
    venv_path  = folder / venv_dir
    venv_found = (venv_path / "Scripts" / "python.exe").exists() or \
                 (venv_path / "bin" / "python").exists()
    hints.append(
        f"✔  Existing venv found: {venv_dir}/" if venv_found
        else f"·  No venv at {venv_dir}/ — will be created on generate"
    )

    # requirements / project files
    has_requirements = (folder / "requirements.txt").exists()
    has_pyproject    = (folder / "pyproject.toml").exists()
    has_setup_py     = (folder / "setup.py").exists() or (folder / "setup.cfg").exists()
    has_uv_lock      = (folder / "uv.lock").exists()

    if has_requirements: hints.append("✔  requirements.txt found")
    if has_pyproject:    hints.append("✔  pyproject.toml found")
    if has_setup_py:     hints.append("✔  setup.py / setup.cfg found")
    if has_uv_lock:      hints.append("✔  uv.lock found")

    # read pyproject.toml for hints
    pyproject_text = ""
    if has_pyproject:
        try:
            pyproject_text = (folder / "pyproject.toml").read_text(encoding="utf-8").lower()
        except OSError:
            pass

    # uv detection
    suggested_use_uv = has_uv_lock or "[tool.uv]" in pyproject_text
    if suggested_use_uv:
        hints.append("→  uv project detected — suggesting uv mode")

    # POSIX suggestion — recommend .sh scripts when not on Windows
    suggested_use_posix = sys.platform != "win32"
    if suggested_use_posix:
        hints.append("→  Non-Windows platform detected — suggesting POSIX .sh scripts")

    # entry point: [project.scripts] first
    suggested_mode:  str | None = None
    suggested_entry: str | None = None
    suggested_args:  str | None = None

    scripts_match = re.search(r"\[project\.scripts\](.*?)(\[|\Z)", pyproject_text, re.DOTALL)
    if scripts_match:
        entry_match = re.search(r'=\s*"([^:"\s]+)', scripts_match.group(1))
        if entry_match:
            module_path    = entry_match.group(1).split(":")[0]
            suggested_mode  = "module"
            suggested_entry = module_path
            suggested_args  = ""
            hints.append(f"→  Entry point from [project.scripts]: {module_path}")

    # dependency keyword scan
    if suggested_mode is None and pyproject_text:
        for keyword, mode, entry, args in _PYPROJECT_HINTS:
            if keyword in pyproject_text:
                suggested_mode  = mode
                suggested_entry = entry
                suggested_args  = args
                hints.append(f"→  Detected {keyword} — suggesting {mode} mode: {entry}")
                break

    # common entry file fallback
    if suggested_mode is None:
        for candidate in ("main.py", "app.py", "__main__.py", "run.py", "cli.py"):
            if (folder / candidate).exists():
                suggested_mode  = "file"
                suggested_entry = candidate
                suggested_args  = ""
                hints.append(f"→  Found {candidate} — suggesting file mode")
                break

    return FolderScan(
        venv_found=venv_found,
        venv_path=venv_path if venv_found else None,
        has_requirements=has_requirements,
        has_pyproject=has_pyproject,
        has_setup_py=has_setup_py,
        has_uv_lock=has_uv_lock,
        suggested_entry_mode=suggested_mode,
        suggested_app_entry=suggested_entry,
        suggested_runner_args=suggested_args,
        suggested_use_uv=suggested_use_uv,
        suggested_use_posix=suggested_use_posix,
        hints=hints,
    )


# ---------------------------------------------------------------------------
# Preset system
# ---------------------------------------------------------------------------

_PRESET_FIELDS = (
    "venv_dir",
    "entry_mode",
    "app_entry",
    "runner_args",
    "overwrite_existing",
    "create_requirements",
    "include_webengine_check",
    "pause_on_exit",
    "create_venv_now",
    "include_test_bat",
    "use_uv",
    "include_posix",
)

_BUILTIN_PRESETS: dict[str, dict] = {
    "CLI Script": {
        "venv_dir": ".venv",
        "entry_mode": "module",
        "app_entry": "app",
        "runner_args": "",
        "overwrite_existing": False,
        "create_requirements": True,
        "include_webengine_check": False,
        "pause_on_exit": True,
        "create_venv_now": False,
        "include_test_bat": True,
        "use_uv": False,
        "include_posix": False,
    },
    "CLI Script (Cross-Platform)": {
        "venv_dir": ".venv",
        "entry_mode": "module",
        "app_entry": "app",
        "runner_args": "",
        "overwrite_existing": False,
        "create_requirements": True,
        "include_webengine_check": False,
        "pause_on_exit": True,
        "create_venv_now": False,
        "include_test_bat": True,
        "use_uv": False,
        "include_posix": True,
    },
    "FastAPI / Uvicorn": {
        "venv_dir": ".venv",
        "entry_mode": "runner",
        "app_entry": "uvicorn",
        "runner_args": "app.main:app --host 0.0.0.0 --port 8000 --reload",
        "overwrite_existing": False,
        "create_requirements": True,
        "include_webengine_check": False,
        "pause_on_exit": False,
        "create_venv_now": False,
        "include_test_bat": True,
        "use_uv": False,
        "include_posix": False,
    },
    "PyQt6 Desktop App": {
        "venv_dir": ".venv",
        "entry_mode": "file",
        "app_entry": "main.py",
        "runner_args": "",
        "overwrite_existing": False,
        "create_requirements": True,
        "include_webengine_check": True,
        "pause_on_exit": True,
        "create_venv_now": False,
        "include_test_bat": False,
        "use_uv": False,
        "include_posix": False,
    },
    "Streamlit App": {
        "venv_dir": ".venv",
        "entry_mode": "runner",
        "app_entry": "streamlit",
        "runner_args": "run app.py",
        "overwrite_existing": False,
        "create_requirements": True,
        "include_webengine_check": False,
        "pause_on_exit": False,
        "create_venv_now": False,
        "include_test_bat": False,
        "use_uv": False,
        "include_posix": False,
    },
    "uv Project": {
        "venv_dir": ".venv",
        "entry_mode": "module",
        "app_entry": "app",
        "runner_args": "",
        "overwrite_existing": False,
        "create_requirements": False,
        "include_webengine_check": False,
        "pause_on_exit": True,
        "create_venv_now": True,
        "include_test_bat": True,
        "use_uv": True,
        "include_posix": False,
    },
}


class PresetManager:
    """Loads and saves user presets to ~/.keystoneai/venv_generator_presets.json.

    Built-in presets are always available and cannot be overwritten or deleted.
    User presets are stored in the JSON file and merged on top of builtins.
    """

    _STORAGE_DIR  = Path.home() / ".keystoneai"
    _STORAGE_FILE = _STORAGE_DIR / "venv_generator_presets.json"

    def __init__(self) -> None:
        self._user: dict[str, dict] = {}
        self._load()

    def names(self) -> list[str]:
        return sorted(_BUILTIN_PRESETS) + sorted(self._user)

    def get(self, name: str) -> dict | None:
        return _BUILTIN_PRESETS.get(name) or self._user.get(name)

    def is_builtin(self, name: str) -> bool:
        return name in _BUILTIN_PRESETS

    def save(self, name: str, data: dict) -> None:
        if name in _BUILTIN_PRESETS:
            raise ValueError(f'"{name}" is a built-in preset and cannot be overwritten.')
        self._user[name] = {k: data[k] for k in _PRESET_FIELDS if k in data}
        self._persist()

    def delete(self, name: str) -> None:
        if name in _BUILTIN_PRESETS:
            raise ValueError(f'"{name}" is a built-in preset and cannot be deleted.')
        if name not in self._user:
            raise KeyError(name)
        del self._user[name]
        self._persist()

    def _load(self) -> None:
        if self._STORAGE_FILE.exists():
            try:
                raw = json.loads(self._STORAGE_FILE.read_text(encoding="utf-8"))
                if isinstance(raw, dict):
                    self._user = raw
            except (json.JSONDecodeError, OSError):
                self._user = {}

    def _persist(self) -> None:
        try:
            self._STORAGE_DIR.mkdir(parents=True, exist_ok=True)
            self._STORAGE_FILE.write_text(
                json.dumps(self._user, indent=2), encoding="utf-8"
            )
        except OSError as exc:
            print(f"[PresetManager] Could not save presets: {exc}", file=sys.stderr)
